[versions]
agp = "8.13.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
lifecycle = "2.7.0"
navigation = '2.7.0'
room = '2.8.3'
playServicesAds = "24.7.0"
playServicesMaps = "19.2.0"
cardview = "1.0.0"
generativeai = "0.9.0"
mpandroidchart = "v3.1.0"
firebaseCrashlyticsBuildtools = "3.0.6"
guavaUtility = "33.5.0-android"
fireBase  = '4.4.4'

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-viewmodel-ktx = {group = 'androidx.lifecycle', name = 'lifecycle-viewmodel-ktx', version.ref = 'lifecycle'}
navigation-fragment-ktx = {group = 'androidx.navigation', name = 'navigation-fragment-ktx', version.ref = 'navigation'}
navigation-ui-ktx = {group = 'androidx.navigation', name = 'navigation-ui-ktx', version.ref = 'navigation'}
room-runtime = {group = 'androidx.room', name = 'room-runtime', version.ref = 'room'}
room-compiler = {group = 'androidx.room', name = 'room-compiler', version.ref = 'room'}
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playServicesAds" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }
guavaUtility = { group = "com.google.guava", name = "guava", version.ref = "guavaUtility" }
fireBase = {group = "com.google.gms.google-services",name = "firebase", version.ref = "fireBase"}
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }




[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

